# fly.toml app configuration file generated for groupchat-wrapped-fe on 2024-12-20T16:33:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'groupchat-wrapped-fe'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
